**Name: Rishi Phadale**  
**Roll No.: 23102C0070**  
**Subject: R Programming**  
## NPTEL Week 7
Worked examples for Sequences, Repeats, Sorting/Ordering/Mode, and Lists

## Sequences

`:` generates a continuous sequence with a constant unit increment, ascending or descending.

In [1]:
1:10
10:1
5:15
15:5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [2]:
-1:-10
-10:-1
-5:-15
-15:-5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

The `:` operator also works with decimal (non-integer) start and end values.

In [3]:
1.23:10
1.23:10.54
10.54:2.23

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [4]:
-1.23:-10
-5.23:6

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

`seq(n)` is a shorthand equivalent to `seq(1:n)`, generating 1 through n.

In [5]:
seq(10)
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

`seq(from, to, by)` builds a sequence using a predefined variable to control the start, end, and step size.

In [6]:
x = 2
seq(1, x, x/10)

x = 50
seq(0, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

 [1]  0  5 10 15 20 25 30 35 40 45 50

The output of `seq()` can be stored in a variable and then reused in further computations.

In [7]:
x = seq(1, 50, 1/2)
x
y = 2*x
y

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

`seq(along = x)` creates an index vector matching the length of `x`, which can then be used to access elements of `x`.

In [8]:
x = c(9,8,7,6)
ind = seq(along = x)
ind
x[ ind[2] ]

[1] 1 2 3 4

[1] 8

`Sys.time()` and `Sys.Date()` return the current date/time and current date from the system clock.

In [9]:
Sys.time()
Sys.Date()

[1] "2026-08-31 16:04:45 UTC"

[1] "2026-08-31"

`seq()` on `Date` objects with `by = "years"` generates a sequence of first-of-year dates between a start and end date.

In [10]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

Using `by = "days"` with `length` generates a sequence of consecutive daily dates of a given length.

In [11]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

Using `by = "months"` generates a sequence of dates incremented one month at a time.

In [12]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

Using `by = "years"` with `length` generates a sequence of dates incremented one year at a time.

In [13]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

A date sequence can also be generated backward between an explicit start and end date using a negative step (e.g. `"-1 month"`).

In [14]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

`letters` is a built-in constant giving the sequence of lowercase English alphabets.

In [15]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

`letters[from_index:to_index]` extracts a sub-sequence of lowercase alphabets by position.

In [16]:
letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

`LETTERS` is a built-in constant giving the sequence of uppercase English alphabets.

In [17]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

`LETTERS[from_index:to_index]` extracts a sub-sequence of uppercase alphabets by position.

In [18]:
LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

## Repeats

`rep(x, times = n)` repeats an entire object `n` times, one full copy after another.

In [19]:
rep(3.5, times = 10)
rep(1:4, 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

`rep(x, each = n)` repeats every single element `n` times before moving to the next element.

In [20]:
x = 1:4
x
rep(x, times = 3)
rep(x, each = 3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

Combining `each` and `times` shows that the order in which they are applied changes the resulting pattern (though here both orders give the same result since they are independent arguments).

In [21]:
rep(1:4, each = 2)
rep(1:4, each = 2, times = 3)
rep(1:4, times = 3, each = 2)

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

Passing a vector to `times` repeats each corresponding element a different number of times.

In [22]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

The repeat-count vector itself can be generated dynamically, e.g. with `seq()`, and then used inside `rep()`.

In [23]:
ans = seq(from = 2, to = 8, by = 2)
ans
rep(1:4, ans)

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

`rep()` also works on non-vector objects such as matrices, repeating their elements in column-major order.

In [24]:
x = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x
rep(x, 3)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

`rep()` works equally well on character vectors, repeating the whole sequence of strings.

In [25]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

`rep(x, length.out = n)` (or `length = n`) repeats values cyclically until the output reaches the specified length.

In [26]:
rep(2, length.out = 5)
rep(2, length = 5)
rep(c(2,3), length = 5)
rep(c(2,3,4), length = 5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

The `length` argument works the same way for character vectors, cycling through values until the target length is reached.

In [27]:
rep("apple", length = 5)
rep(c("a", "b", "c"), length = 2)
rep(c("a", "b", "c"), length = 5)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

## Sorting

`sort()` arranges the values of a vector in ascending order by default, or descending order with `decreasing = TRUE`.

In [28]:
y = c(8,5,7,6)
y
sort(y)
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

## Ordering

`order()` returns the positions (indices) that would arrange the vector in sorted order, rather than the sorted values themselves.

In [29]:
y = c(9,8,5,7,6)
y
order(y)
order(y, decreasing = TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

## Mode

`mode()` reports how an R object is stored internally, e.g. numeric, character, list, or function.

In [30]:
mode(2.432)
mode(c(3,4,5,6,7,8))
mode("India")
mode(c("India", "CANADA"))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

Factors, lists, and data frames report their mode according to their internal storage type, and functions report mode `"function"`.

In [31]:
mode(factor(c("UP", "MP")))
mode(list("India", "USA"))
mode(data.frame(x = 1:2, y = c("India", "USA")))
mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

## Lists

Ordinary vectors and matrices can only hold one data type, so adding two numeric matrices works via elementwise arithmetic.

In [32]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = TRUE)
x1
x2
x1 + x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

Assigning a character value into a numeric matrix coerces the whole matrix to character mode, so arithmetic on it then fails.

In [33]:
x1[2,1] = "hello"
x1
x1 + x2

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

ERROR: Error in x1 + x2: non-numeric argument to binary operator

A `list()`, unlike a matrix, can hold elements of different types or structures — here two matrices are stored together as list elements.

In [34]:
matlist = list(x1 <- matrix(nrow = 2, ncol = 2, data = 1:4, byrow = TRUE), x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

Single-bracket indexing `matlist[i]` returns a sub-list (still wrapped in `[[ ]]`), preserving the list structure.

In [35]:
matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

A list can mix entirely different object types together, such as a character vector, a numeric vector, and a matrix in one list.

In [36]:
z1 = list( c("water", "juice", "lemonade"), rep(1:4, each = 2), matrix(data = 5:8, nrow = 2, ncol = 2, byrow = TRUE) )
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

Double brackets `[[ ]]` extract the actual list element, while single brackets `[ ]` keep it wrapped as a list — so `z1[[1]][2]` reaches the value, but `z1[1][2]` returns `NULL`.

In [37]:
z1[[1]]
z1[1][2]
z1[[1]][2]

[1] "water"    "juice"    "lemonade"

[[1]]
NULL

[1] "juice"