## NPTEL- Week 4

In [1]:
x=matrix(nrow=4, ncol=3, data=c(1:12))
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [2]:
rownames(x) = c("r1", "r2", "r3", "r4")
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [3]:
colnames(x) = c("c1", "c2", "c3")
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [4]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

In [5]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [6]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [7]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [8]:
xt = t(x)
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [9]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [10]:
rowSums(x)
colSums(x)

[1]  6  8 10 12

[1] 10 26

In [11]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [12]:
rowMeans(x)
colMeans(x)

[1] 3 4 5 6

[1] 2.5 6.5

In [13]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x
x[3,]
x[,2]
x[4:5, 2:3]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [14]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [17]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

x+5

x-5

5*x

x/2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

In [18]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [19]:
x
y

x+y

x-y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [20]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

4*x

x+4*x

4*x-x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

In [21]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [22]:
x%*%y #matrix multiplication

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [23]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

In [24]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [25]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [26]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [27]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

In [28]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [29]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [30]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y

rbind(x,y)
cbind(x,y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [31]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [32]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [33]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [34]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [38]:
x = c(8,18)

In [40]:
(x < 10) || (x < 2)

ERROR: Error in (x < 10) || (x < 2): 'length = 2' in coercion to 'logical(1)'

In [37]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [41]:
x = 5
(x < 10) && (x > 2)

[1] TRUE

In [42]:
x = 15
(x < 10) && (x > 2)

[1] FALSE

In [43]:
x = c(8,18)
(x < 10) && (x > 2)

ERROR: Error in (x < 10) && (x > 2): 'length = 2' in coercion to 'logical(1)'

In [44]:
(x < 10) & (x > 2)

[1]  TRUE FALSE

In [45]:
x=1:6
(x>2)&(x<5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [46]:
x[(x > 2) & (x < 5)]

[1] 3 4

In [49]:
x = 1:6
(x > 2) | (x < 5)

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [50]:
x[(x > 2) | (x < 5)]

[1] 1 2 3 4 5 6

In [51]:
(x > 2) && (x < 5)

ERROR: Error in (x > 2) && (x < 5): 'length = 6' in coercion to 'logical(1)'

In [52]:
(x[1] > 2) & (x[1] < 5)

[1] FALSE

In [53]:
x = TRUE
y = FALSE
x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

In [54]:
x=5
Logical1 = (x > 2)
Logical1
is.logical(Logical1)

[1] TRUE

[1] TRUE

In [55]:
Logical2 = (x < 10)
Logical2
is.logical(Logical2)

[1] TRUE

[1] TRUE

In [56]:
Logical3 = (x != 5)
Logical3
is.logical(Logical3)

[1] FALSE

[1] TRUE

In [57]:
x = 5
Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)

[1] FALSE

[1] TRUE

In [58]:
Logical5 = (3*x <20)
Logical5
is.logical(Logical5)

[1] TRUE

[1] TRUE

In [59]:
8>7
7<5
7>7
7>=7
8<8
8<=8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

In [61]:
8 != 9
9 != 9
7 == 7
7 == 8
x = TRUE
!x

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

In [62]:
x = c(1, 2, 3)
y = c(4, 5, 6)

In [63]:
x>y
x<y
x!=y
x==y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [64]:
isTRUE(8 < 6)

isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

In [68]:
x=matrix(seq(5,32,2),4,4,byrow=F)
rowSums(x)
colSums(x)

Warning message in matrix(seq(5, 32, 2), 4, 4, byrow = F):
“data length [14] is not a sub-multiple or multiple of the number of rows [4]”

[1] 68 76 56 64

[1] 32 64 96 72

[1] 17 19 14 16

In [72]:
x=matrix(seq(5,35,2),4,4,byrow=F)
rowMeans(x)
colMeans(x)

[1] 17 19 21 23

[1]  8 16 24 32

In [71]:
x=matrix(seq(9,39,2),4,4,byrow=F)
colMeans(x)

[1] 12 20 28 36

In [74]:
x=diag(c(6,7,8),nrow=3,ncol=3)
x

     [,1] [,2] [,3]
[1,] 6    0    0
[2,] 0    7    0
[3,] 0    0    8

In [75]:
x=matrix(nrow=4,ncol=2,data=18:11,byrow=T)
t(x)

     [,1] [,2] [,3] [,4]
[1,] 18   16   14   12
[2,] 17   15   13   11

In [76]:
x=matrix(nrow=2,ncol=4,data=24:31,byrow=T)
3*x

     [,1] [,2] [,3] [,4]
[1,] 72   75   78   81
[2,] 84   87   90   93

In [77]:
x=matrix(nrow=4,ncol=4,data=24:39,byrow=F)
12-3%*%x

ERROR: Error in 3 %*% x: non-conformable arguments

In [78]:
x=matrix(nrow=4,ncol=4,data=5:20,byrow=T)
x[2,]

[1]  9 10 11 12

In [79]:
x=matrix(nrow=4,ncol=4,data=5:20,byrow=F)
x[3:4,1:2]

     [,1] [,2]
[1,] 7    11
[2,] 8    12

In [82]:
x=matrix(nrow=4,ncol=3,data=1:12,byrow=T)
x
x[1:2,c(2,3)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

     [,1] [,2]
[1,] 2    3
[2,] 5    6

In [84]:
x=matrix(nrow=2,ncol=3,data=1:6,byrow=F)
y=matrix(nrow=2,ncol=3,data=7:12,byrow=F)
X=cbind(x,y)
X

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    3    5    7     9   11
[2,] 2    4    6    8    10   12

In [85]:
Y=rbind(x,y)
Y

     [,1] [,2] [,3]
[1,] 1     3    5
[2,] 2     4    6
[3,] 7     9   11
[4,] 8    10   12

In [86]:
x=21
(x<25)||(x>22)&(x<25)&&(x>22)||(x==27)

[1] TRUE

In [87]:
x=45
(x<25)||(x>22)&(x<25)&&(x>22)||(x==27)

[1] FALSE

In [88]:
x=3:6
(x>4)&(x<7)

[1] FALSE FALSE  TRUE  TRUE