## R Programming - Week 2 and 3

In [2]:
#Addition with data
c(2,3,5,7) + c(-2,-3, -5, 8)

[1]  0  0  0 15

In [3]:
c(2,3,5,7) + c(8,9)

[1] 10 12 13 16

In [4]:
c(2,3,5,7) + c(8,9,10)

Warning message in c(2, 3, 5, 7) + c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 10 12 15 15

In [5]:
#Subtraction with data vectors
c(2,3,5,7) - c(-2,-3, -5, 8)

[1]  4  6 10 -1

In [6]:
c(12,13,15,17) - c(8,9)

[1] 4 4 7 8

In [7]:
c(12,13,15,17) - c(8,9,10)

Warning message in c(12, 13, 15, 17) - c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 4 4 5 9

In [8]:
#Multiplication with data vectors
c(2,3,5,7) * c(-2,-3,-5,8)

[1]  -4  -9 -25  56

In [9]:
c(2,3,5,7) * c(8,9)

[1] 16 27 40 63

In [11]:
c(2,3,5,7) * c(8,9,10)

Warning message in c(2, 3, 5, 7) * c(8, 9, 10):
“longer object length is not a multiple of shorter object length”

[1] 16 27 50 56

In [13]:
#Division with data vectors
c(24,20,8,16) / c(3,4,2,8)

[1] 8 5 4 2

In [14]:
c(24,20,8,16)/c(4,2)

[1]  6 10  2  8

In [15]:
c(24,20,8,16) / c(4,2,8)

Warning message in c(24, 20, 8, 16)/c(4, 2, 8):
“longer object length is not a multiple of shorter object length”

[1]  6 10  1  4

### Assignment of Numbers and Characters

In [17]:
x=20
x

[1] 20

In [19]:
x <- 40
x

[1] 40

In [20]:
x=apple
x

ERROR: Error: object 'apple' not found

In [21]:
x='apple'
x

[1] "apple"

In [22]:
x=20
is.numeric(x)

is.character(x)

y='apple'
is.character(y)
is.numeric(y)

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

In [23]:
#converting numbers and characters
x=20
is.numeric(x)

y=as.character(x)
is.numeric(y)
is.character(y)

y

[1] TRUE

[1] FALSE

[1] TRUE

[1] "20"

In [26]:
y='apple'
is.numeric(y)

is.character(y)

z=as.numeric(y)
is.numeric(z)
z

[1] FALSE

[1] TRUE

Warning message:
“NAs introduced by coercion”

[1] TRUE

[1] NA

In [27]:
#comments
#case sensitivity
x=20
X

ERROR: Error: object 'X' not found

In [28]:
y=1,2,3,4,5
y

ERROR: Error in parse(text = input): <text>:1:4: unexpected ','
1: y=1,
       ^

The command c(1,2,3,4,5) combines the numbers
1,2,3,4 and 5 to a vector.

In [29]:
y=c(1,2,34,5)
y

[1]  1  2 34  5

In [31]:
#mode
x=6
x
mode(x)

y='apple'
y
mode(y)

[1] 6

[1] "numeric"

[1] "apple"

[1] "character"

In [33]:
storage.mode(x)
storage.mode(y)
z=TRUE
storage.mode(z)

[1] "double"

[1] "character"

[1] "logical"

In [34]:
3/0

[1] Inf

In [35]:
5+Inf

[1] Inf

In [38]:
x=6+Inf
is.infinite(x)
is.finite(x)

[1] TRUE

[1] FALSE

In [39]:
2+3
2*5
3/2
2-4
2*3-4+5/6

[1] 5

[1] 10

[1] 1.5

[1] -2

[1] 2.833333

In [41]:
(2+3)*5 + 5 - 10

[1] 20

In [42]:
(((2+3)*5 + 5) - 10)/2

[1] 10

In [44]:
2     +      5
#blank space - no role

[1] 7

In [45]:
#addition with scalar
c(2,3,5,7)+10

[1] 12 13 15 17

In [46]:
#subtraction with scalar
c(  12,13,15,17) - 10

[1] 2 3 5 7

In [47]:
#multiplication with scalar
c(12,13,15,17) * 10

[1] 120 130 150 170

In [48]:
#division with scalar
c(12,13,15,17) / 10

[1] 1.2 1.3 1.5 1.7

In [50]:
#addition with data vectors
c(2,3,5,7) + c(-2,-3, -5, 8)

[1]  0  0  0 15

In [51]:
#power operator
2^3
2**3
2^0.5
2**0.5
2^-0.5

#power operator with scalar
c(2,3,5,7)^2

#power operator with vector
c(2,3,5,7)^c(2,3)

c(1,2,3,4,5,6)^c(2,3,4)

c(2,3,5,7)^c(2,3,4)

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

[1]  4  9 25 49

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [56]:
#integer division with scalar
#division in which the fractional part(remainder) is discarded

2 %/% 2
7 %/% 3


#integer division with scalar
c(2,3,4,5,6) %/% 2

#integer division with data vector
c(2,3,5,7) %/% c(2,3)

[1] 1

[1] 2

[1] 1 1 2 2 3

[1] 1 1 2 2

In [60]:
#modulo div with scalars
2 %% 2
7 %% 3

c(2,3,5,7) %% 2

c(2,3,5,7) %% c(2,3)

c(2,3,5) %% c(2,3)

[1] 0

[1] 1

[1] 0 1 1 1

[1] 0 0 1 1

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [64]:
#functions
#max
max(1.2, 3.4, -7.8)
max(c(1.2,3.4,-7.8))

#min
min(1.2, 3.4, -7.8)
min(c(1.2,3.4,-7.8))

#mean
mean(2,3,4)
mean(c(2,3,4))

#abs
abs(-4)
abs(c(-1,-2,-3,-4,5))

#sqrt
sqrt(4)
sqrt(c(4,9,16,26,36))

#sum
sum(5,10,15)
sum(c(5,10,15))

#round
round(1.23)
round(1.83)

#log
log(10)
log(exp(1))
log(c(10,100,1000))

#log10
log10(10)
log10(100)

[1] 3.4

[1] 3.4

[1] -7.8

[1] -7.8

[1] 2

[1] 3

[1] 4

[1] 1 2 3 4 5

[1] 2

[1] 2.00000 3.00000 4.00000 5.09902 6.00000

[1] 30

[1] 30

[1] 1

[1] 2

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

[1] 1

[1] 2

In [65]:
x1=c(1,2,3,4)
x1

x2=x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [66]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))

[1] 21 22 23 24

In [67]:
abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)) )

[1] 19 18 17 16

In [69]:
#Matrix
x=matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [70]:
x[3,2]

[1] 7

In [72]:
#column wise data entry
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = FALSE)
y

#rowwise
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [74]:
#propertise
dim(x)
nrow(x)
ncol(x)
mode(x)
attributes(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [75]:
help("matrix")

In [78]:
is.matrix(as.matrix(1:10))

[1] TRUE

In [80]:
data(warpbreaks)

In [83]:
!is.matrix(warpbreaks)

[1] TRUE

In [85]:
warpbreaks[1:10,]

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

In [86]:
as.matrix(warpbreaks[1:10,])

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M